apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  argocd/app-name: k29p8e8r6-java-quarkus
  janus-idp.io/tekton: k29p8e8r6-java-quarkus
  backstage.io/kubernetes-id: k29p8e8r6-java-quarkus
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: k29p8e8r6-java-quarkus
resources:
- deployment.yaml
- route.yaml
- service.yaml
